CREATE TABLE item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255),
                      description TEXT,
                      img_path VARCHAR(255),
                      price DECIMAL(10,2)
);

CREATE TABLE cart (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           item_id BIGINT NOT NULL,
                           count INT,
                           cart_id BIGINT,
                           CONSTRAINT fk_cart_item_item FOREIGN KEY(item_id) REFERENCES item(id),
                           CONSTRAINT fk_cart_item_cart FOREIGN KEY(cart_id) REFERENCES cart(id)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        total DECIMAL(10,2)
);

CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            item_id BIGINT NOT NULL,
                            count INT,
                            order_id BIGINT,
                            CONSTRAINT fk_order_item_item FOREIGN KEY(item_id) REFERENCES item(id),
                            CONSTRAINT fk_order_item_order FOREIGN KEY(order_id) REFERENCES orders(id)
);
