DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL
);


CREATE TABLE item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255),
                      description TEXT,
                      img_path VARCHAR(255),
                      price DECIMAL(10,2)
);

CREATE TABLE cart (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL UNIQUE,
                      CONSTRAINT fk_cart_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           item_id BIGINT NOT NULL,
                           count INT,
                           cart_id BIGINT,
                           CONSTRAINT fk_cart_item_item FOREIGN KEY(item_id) REFERENCES item(id),
                           CONSTRAINT fk_cart_item_cart FOREIGN KEY(cart_id) REFERENCES cart(id)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        total DECIMAL(10,2),
                        user_id BIGINT NOT NULL,
                        CONSTRAINT fk_order_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            item_id BIGINT NOT NULL,
                            count INT,
                            order_id BIGINT,
                            CONSTRAINT fk_order_item_item FOREIGN KEY(item_id) REFERENCES item(id),
                            CONSTRAINT fk_order_item_order FOREIGN KEY(order_id) REFERENCES orders(id)
);