server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          main-shop-client:
            registration:
              client-id: main-shop-client
              client-secret: "{noop}secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - payments.read
