services:
  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  payments:
    build:
      context: ../payments
      dockerfile: Dockerfile
    container_name: payments
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      SPRING_SECURITY_OAUTH2_URI: http://auth-server:9000
    restart: unless-stopped

  auth-server:
    build:
      context: ../auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    ports:
      - "9000:9000"
    restart: unless-stopped

  main-shop:
    build:
      context: ../main-shop
      dockerfile: Dockerfile
    container_name: main-shop
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - payments
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      PAYMENTS_SERVICE_URL: http://payments:8081
      SPRING_SECURITY_OAUTH2_URI: http://auth-server:9000
    restart: unless-stopped

volumes:
  redis_data:
