version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # enables persistence
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
